sudo: false
os: linux
language: 
  - cpp
  - python
compiler:
  - gcc
  - llvm
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - gcc-5
      - g++-5
      - gfortran-5
      - libopenmpi-dev
      - libblas-dev
      - liblapack-dev
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]] || [[ "$TRAVIS_PYTHON_VERSION" == "2.6" ]] ; then
      export PYTHONMAJORV=2;
    else
      export PYTHONMAJORV=3;
    fi
  - wget https://repo.continuum.io/miniconda/Miniconda${PYTHONMAJORV}-latest-Linux-x86_64.sh
  - bash Miniconda${PYTHONMAJORV}-latest-Linux-x86_64.sh -b
  - export PATH=$HOME/miniconda${PYTHONMAJORV}/bin:$PATH
  - conda create -n mypy python=$TRAVIS_PYTHON_VERSION
  - source activate mypy
  - conda install -y cython
  - conda install -y numpy  
  - conda install -y mpich2  
install:
  - ./configure CXX=mpicxx
  - make -j2 
  - make python -j2
script:
  - make test
  - make test2
  - make test_python
  - make test_python2
after_failure:
notifications:
  email:
    recipients:
      - solomon2@illinois.edu
    on_success: change
    on_failure: always


