sudo: false
os: linux
language: 
  - cpp
  - python
compiler:
  - gcc
  - llvm
python:
#  - "2.6"
#  - "2.7"
#  - "3.3"
  - "3.4"
#  - "3.5"
#  - "3.5-dev"  # 3.5 development branch
#  - "3.6"
#  - "3.6-dev"  # 3.6 development branch
#  - "3.7-dev"  # 3.7 development branch
# command to install dependencies

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - gcc-5
      - g++-5
      - gfortran-5
      - libopenmpi-dev
      - libblas-dev
      - liblapack-dev
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH
  - conda install -y cython
  - conda install -y numpy  
  - conda install -y mpich2  
install:
  - ./configure CXX=mpicxx
  - make -j2 
  - make python -j2
script:
  - make test
  - make test2
  - make test_python
  - make test_python2
after_failure:
notifications:
  email:
    recipients:
      - solomon2@illinois.edu
    on_success: change
    on_failure: always


