sudo: false
os:
  - linux
  - osx
language: 
  - cpp
  - python
compiler:
  - gcc
  - llvm
language: python
python:
#  - "2.6"
#  - "2.7"
#  - "3.3"
  - "3.4"
#  - "3.5"
#  - "3.5-dev"  # 3.5 development branch
#  - "3.6"
#  - "3.6-dev"  # 3.6 development branch
#  - "3.7-dev"  # 3.7 development branch
# command to install dependencies

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - gcc-5
      - g++-5
      - gfortran-5
      - libopenmpi-dev
      - libblas-dev
      - liblapack-dev
before_install:
  - pwd
  - export TRAVIS_HOME=$PWD
  - export PATH=$TRAVIS_HOME/deps/bin:$PATH
install:
  - mkdir -p $TRAVIS_HOME/deps
  - sh ./travis/install-mpi.sh $TRAVIS_HOME/deps mpich
  - pip install --force-reinstall numpy
  - pip install cython
before_script:
  - which mpicxx ; mpicxx -v
  - ./configure CXX=mpicxx
script:
  - make
  - make test
  - make test2
  - make python
  - make test_base
after_failure:
notifications:
  email:
    recipients:
      - solomon2@illinois.edu
    on_success: change
    on_failure: always


